// recipes/recipes.js — executable lookup/formula cell fragments from the catalog.
//
// COMPATIBILITY CONTRACT (with the arena engine, /home/z/my-project/download/quilt-arena/engine):
//   kind 'lookup'  → a value/lookup cell: { table: {input: output}, default } — the
//                    engine's value cells hold data; tables are the formulaic bulk.
//   kind 'formula' → the engine's formula cell: `expr` is a tiny DSL evaluated with
//                    `new Function` + declared input names in scope (NOT a security
//                    boundary — same trust level as the upstream engine's formula.js).
// Every recipe carries example_input + expected_output so src/validate.js can prove
// it executable. catalog_ref points back at the spreadsheet-types entry it came from.

export const RECIPES = [
  // ---- SET THEORY ----
  { id: 'set.membership', kind: 'lookup', family: 'set-theory', catalog_ref: 'set-membership-table',
    inputs: ['element_set'], table: { 'alice:read': 1, 'alice:write': 1, 'bob:read': 1, 'bob:write': 0 }, default: 0,
    example_input: { element_set: 'alice:write' }, expected_output: 1,
    note: 'skills/access matrix: rows=elements, cols=sets' },
  { id: 'set.inclusion-exclusion', kind: 'formula', family: 'set-theory', catalog_ref: 'inclusion-exclusion-table',
    inputs: ['a', 'b', 'ab'], expr: 'a + b - ab',
    example_input: { a: 40, b: 30, ab: 10 }, expected_output: 60 },
  { id: 'set.cardinality', kind: 'formula', family: 'set-theory', catalog_ref: 'cardinality-table',
    inputs: ['items'], expr: 'items.length',
    example_input: { items: ['x', 'y', 'z'] }, expected_output: 3 },
  { id: 'set.partition', kind: 'lookup', family: 'set-theory', catalog_ref: 'partition-table',
    inputs: ['customer_spend'], table: { low: 'starter', mid: 'regular', high: 'vip' }, default: 'starter',
    example_input: { customer_spend: 'mid' }, expected_output: 'regular' },

  // ---- RELATIONS & FUNCTIONS ----
  { id: 'rel.function-table', kind: 'lookup', family: 'relations-functions', catalog_ref: 'function-table',
    inputs: ['taxable_income_bracket'], table: { b1: 0.10, b2: 0.22, b3: 0.32 }, default: 0.32,
    example_input: { taxable_income_bracket: 'b2' }, expected_output: 0.22,
    note: 'the canonical lookup: tax brackets' },
  { id: 'rel.composition', kind: 'lookup', family: 'relations-functions', catalog_ref: 'composition-table',
    inputs: ['via'], table: { a: 'b', b: 'c', c: 'd' }, default: null,
    example_input: { via: 'a' }, expected_output: 'b' },
  { id: 'rel.transitive-closure', kind: 'formula', family: 'relations-functions', catalog_ref: 'transitive-closure-table',
    inputs: ['hops', 'max'], expr: 'hops <= max ? "reachable" : "unreachable"',
    example_input: { hops: 3, max: 3 }, expected_output: 'reachable' },

  // ---- LOGIC ----
  { id: 'logic.and', kind: 'lookup', family: 'logic', catalog_ref: 'truth-table',
    inputs: ['a_b'], table: { '00': 0, '01': 0, '10': 0, '11': 1 }, default: 0,
    example_input: { a_b: '11' }, expected_output: 1 },
  { id: 'logic.or', kind: 'lookup', family: 'logic', catalog_ref: 'truth-table',
    inputs: ['a_b'], table: { '00': 0, '01': 1, '10': 1, '11': 1 }, default: 1,
    example_input: { a_b: '01' }, expected_output: 1 },
  { id: 'logic.xor', kind: 'lookup', family: 'logic', catalog_ref: 'truth-table',
    inputs: ['a_b'], table: { '00': 0, '01': 1, '10': 1, '11': 0 }, default: 0,
    example_input: { a_b: '10' }, expected_output: 1 },
  { id: 'logic.implies', kind: 'lookup', family: 'logic', catalog_ref: 'truth-table',
    inputs: ['a_b'], table: { '00': 1, '01': 1, '10': 0, '11': 1 }, default: 1,
    example_input: { a_b: '10' }, expected_output: 0 },
  { id: 'logic.decision-table', kind: 'lookup', family: 'logic', catalog_ref: 'decision-table',
    inputs: ['member_cart_total'], table: { 'yes_0': 'no-action', 'yes_50': 'member-discount', 'no_50': 'upsell-membership' }, default: 'no-action',
    example_input: { member_cart_total: 'yes_50' }, expected_output: 'member-discount' },

  // ---- LINEAR ALGEBRA ----
  { id: 'la.dot2', kind: 'formula', family: 'linear-algebra', catalog_ref: 'gram-matrix',
    inputs: ['a1', 'a2', 'b1', 'b2'], expr: 'a1*b1 + a2*b2',
    example_input: { a1: 1, a2: 2, b1: 3, b2: 4 }, expected_output: 11,
    note: 'Gram matrix entry: the inner product of two 2-vectors' },
  { id: 'la.det2', kind: 'formula', family: 'linear-algebra', catalog_ref: 'matrix-table',
    inputs: ['a', 'b', 'c', 'd'], expr: 'a*d - b*c',
    example_input: { a: 1, b: 2, c: 3, d: 4 }, expected_output: -2 },
  { id: 'la.transpose-lookup', kind: 'lookup', family: 'linear-algebra', catalog_ref: 'sparse-matrix-table',
    inputs: ['cell'], table: { 'r1c2': 'c1r2', 'r2c3': 'c2r3', 'r3c1': 'c3r1' }, default: null,
    example_input: { cell: 'r2c3' }, expected_output: 'c2r3',
    note: 'sparse coordinate storage: (row,col) -> (col,row) transpose' },
  { id: 'la.trace', kind: 'formula', family: 'linear-algebra', catalog_ref: 'matrix-table',
    inputs: ['a11', 'a22'], expr: 'a11 + a22',
    example_input: { a11: 5, a22: 7 }, expected_output: 12 },

  // ---- PROBABILITY & STATISTICS ----
  { id: 'stat.mean', kind: 'formula', family: 'probability-statistics', catalog_ref: 'frequency-table',
    inputs: ['xs'], expr: 'xs.reduce((s, x) => s + x, 0) / xs.length',
    example_input: { xs: [2, 4, 6] }, expected_output: 4,
    note: 'the tally that summarizes a tally' },
  { id: 'stat.variance', kind: 'formula', family: 'probability-statistics', catalog_ref: 'covariance-matrix',
    inputs: ['xs', 'mu'], expr: 'xs.reduce((s, x) => s + (x - mu) * (x - mu), 0) / xs.length',
    example_input: { xs: [2, 4, 6], mu: 4 }, expected_output: 2.6666666666666665,
    note: 'diagonal covariance entry for one variable' },
  { id: 'stat.zscore', kind: 'formula', family: 'probability-statistics', catalog_ref: 'z-table',
    inputs: ['x', 'mu', 'sd'], expr: '(x - mu) / sd',
    example_input: { x: 10, mu: 8, sd: 2 }, expected_output: 1,
    note: 'standardization: the input the z-table consumes' },
  { id: 'prob.coin-entropy', kind: 'formula', family: 'probability-statistics', catalog_ref: 'entropy-table',
    inputs: ['p'], expr: 'p <= 0 || p >= 1 ? 0 : -(p * Math.log2(p) + (1 - p) * Math.log2(1 - p))',
    example_input: { p: 0.5 }, expected_output: 1 },
  { id: 'prob.expected-value', kind: 'formula', family: 'probability-statistics', catalog_ref: 'probability-distribution-table',
    inputs: ['px', 'vx', 'py', 'vy'], expr: 'px * vx + py * vy',
    example_input: { px: 0.5, vx: 10, py: 0.5, vy: -2 }, expected_output: 4 },

  // ---- OPTIMIZATION / OR ----
  { id: 'opt.linear-interp', kind: 'formula', family: 'optimization-or', catalog_ref: 'interpolation-table',
    inputs: ['x', 'x0', 'y0', 'x1', 'y1'], expr: 'x1 === x0 ? y0 : y0 + (y1 - y0) * (x - x0) / (x1 - x0)',
    example_input: { x: 15, x0: 10, y0: 100, x1: 20, y1: 200 }, expected_output: 150 },
  { id: 'opt.knapsack-yes', kind: 'lookup', family: 'optimization-or', catalog_ref: 'decision-table',
    inputs: ['weight_budget'], table: { '5': 'fits', '8': 'fits', '9': 'over' }, default: 'over',
    example_input: { weight_budget: '8' }, expected_output: 'fits' },

  // ---- GRAPH & NETWORK ----
  { id: 'graph.degree', kind: 'lookup', family: 'graph-network', catalog_ref: 'degree-table',
    inputs: ['vertex'], table: { a: 3, b: 2, c: 1 }, default: 0,
    example_input: { vertex: 'a' }, expected_output: 3 },
  { id: 'graph.reachable-1hop', kind: 'lookup', family: 'graph-network', catalog_ref: 'adjacency-table',
    inputs: ['from'], table: { a: 'b,c', b: 'c', c: '' }, default: '',
    example_input: { from: 'b' }, expected_output: 'c' },
  { id: 'graph.edge-exists', kind: 'lookup', family: 'graph-network', catalog_ref: 'adjacency-matrix',
    inputs: ['pair'], table: { 'a-b': 1, 'b-c': 1, 'c-a': 0 }, default: 0,
    example_input: { pair: 'b-c' }, expected_output: 1 },

  // ---- NUMBER THEORY & COMBINATORICS ----
  { id: 'nt.gcd-pair', kind: 'lookup', family: 'number-theory-combinatorics', catalog_ref: 'multiplication-table-mod-n',
    note2: 'gcd via modular arithmetic family; precomputed pairs',
    inputs: ['pair'], table: { '8-12': 4, '7-13': 1, '9-27': 9 }, default: 1,
    example_input: { pair: '9-27' }, expected_output: 9,
    note: 'precomputed gcd pairs; the algorithmic cell generalizes' },
  { id: 'nt.mod-class', kind: 'formula', family: 'number-theory-combinatorics', catalog_ref: 'equivalence-class-table',
    inputs: ['n'], expr: 'n % 3',
    example_input: { n: 10 }, expected_output: 1 },
  { id: 'nt.comb-choose2', kind: 'formula', family: 'number-theory-combinatorics', catalog_ref: 'binomial-table',
    inputs: ['n'], expr: 'n * (n - 1) / 2',
    example_input: { n: 5 }, expected_output: 10 },

  // ---- CS & DISCRETE ----
  { id: 'cs.bit-pair', kind: 'lookup', family: 'cs-discrete-tables', catalog_ref: 'truth-table',
    inputs: ['op_ab'], table: { 'and_00': 0, 'and_11': 1, 'or_01': 1, 'xor_10': 1 }, default: 0,
    example_input: { op_ab: 'xor_10' }, expected_output: 1 },
  { id: 'cs.round-half', kind: 'formula', family: 'cs-discrete-tables', catalog_ref: 'fixed-point-table',
    inputs: ['x'], expr: 'Math.round(x)',
    example_input: { x: 2.5 }, expected_output: 3,
    note: 'rounding mode: half-up as a table of one rule' },

  // ---- INFORMATION THEORY (extension family) ----
  { id: 'it.huffman-bias', kind: 'lookup', family: 'information-theory', catalog_ref: 'codebook-table',
    inputs: ['symbol'], table: { e: '0', t: '10', a: '110', rare: '1110' }, default: '1111',
    example_input: { symbol: 't' }, expected_output: '10' },
  { id: 'it.redundancy-parity', kind: 'formula', family: 'information-theory', catalog_ref: 'redundancy-table',
    inputs: ['bits'], expr: 'bits.length % 2',
    example_input: { bits: [1, 0, 1] }, expected_output: 1 },
  { id: 'it.typewriter', kind: 'lookup', family: 'information-theory', catalog_ref: 'typewriter-channel-table',
    inputs: ['typed'], table: { q: 'w', w: 'e', e: 'r' }, default: 'q',
    example_input: { typed: 'q' }, expected_output: 'w',
    note: 'typewriter channel: adjacent-key confusion as a channel matrix row' },
  { id: 'it.kl-drift', kind: 'formula', family: 'information-theory', catalog_ref: 'kl-divergence-table',
    inputs: ['p', 'q'], expr: 'p*Math.log(p/q) + (1-p)*Math.log((1-p)/(1-q))',
    example_input: { p: 0.5, q: 0.25 }, expected_output: 0.14384103622589042,
    note: 'KL between two Bernoullis (nats): the drift row of the divergence table' },
  { id: 'it.mutual-info', kind: 'formula', family: 'information-theory', catalog_ref: 'mutual-information-table',
    inputs: ['hx', 'hy', 'hxy'], expr: 'hx + hy - hxy',
    example_input: { hx: 1, hy: 1, hxy: 0.5 }, expected_output: 1.5,
    note: 'I(X;Y) = H(X)+H(Y)-H(X,Y) in bits; shared information between two variables' },

  // ---- GAME THEORY (extension family) ----
  { id: 'gt.payoff', kind: 'lookup', family: 'game-theory', catalog_ref: 'payoff-matrix',
    inputs: ['cell'], table: { 'cooperate-cooperate': 3, 'cooperate-defect': 0, 'defect-cooperate': 5, 'defect-defect': 1 }, default: 1,
    example_input: { cell: 'defect-cooperate' }, expected_output: 5,
    note: "prisoner's dilemma: rows=own action, cols=other's" },
  { id: 'gt.best-response', kind: 'lookup', family: 'game-theory', catalog_ref: 'best-response-table',
    inputs: ['opp'], table: { rock: 'paper', paper: 'scissors', scissors: 'rock' }, default: 'rock',
    example_input: { opp: 'paper' }, expected_output: 'scissors' },
  { id: 'gt.nash-check', kind: 'formula', family: 'game-theory', catalog_ref: 'nash-table',
    inputs: ['own_payoff', 'dev_payoff'], expr: 'own_payoff >= dev_payoff ? "nash" : "deviate"',
    example_input: { own_payoff: 3, dev_payoff: 3 }, expected_output: 'nash',
    note: 'a profile is Nash iff no unilateral deviation improves; ties hold' },
  { id: 'gt.saddle-check', kind: 'formula', family: 'game-theory', catalog_ref: 'zero-sum-table',
    inputs: ['maximin', 'minimax'], expr: 'maximin === minimax ? "saddle" : "mixed"',
    example_input: { maximin: 2, minimax: 2 }, expected_output: 'saddle',
    note: 'zero-sum games: equal maximin/minimax means a pure saddle point exists' },
  { id: 'gt.shapley-2', kind: 'formula', family: 'game-theory', catalog_ref: 'cooperative-table',
    inputs: ['v_a', 'v_b', 'v_ab'], expr: 'v_a + (v_ab - v_a - v_b) / 2',
    example_input: { v_a: 3, v_b: 4, v_ab: 10 }, expected_output: 4.5,
    note: '2-player Shapley: own standalone value + half the synergy of the coalition' },

  // ---- CONTROL THEORY (extension family) ----
  { id: 'ctl.setpoint', kind: 'lookup', family: 'control-theory', catalog_ref: 'setpoint-table',
    inputs: ['mode'], table: { eco: 18, comfort: 21, boost: 24 }, default: 21,
    example_input: { mode: 'comfort' }, expected_output: 21,
    note: 'thermostat operating points' },
  { id: 'ctl.deadband', kind: 'formula', family: 'control-theory', catalog_ref: 'gain-margin-table',
    inputs: ['err', 'band'], expr: 'Math.abs(err) < band ? 0 : err',
    example_input: { err: 0.2, band: 0.5 }, expected_output: 0 },
  { id: 'ctl.phase-margin-rule', kind: 'lookup', family: 'control-theory', catalog_ref: 'phase-margin-table',
    inputs: ['margin_band'], table: { '<30': 'unstable-risk', '30-45': 'marginal', '45-60': 'good', '>60': 'robust' }, default: 'unstable-risk',
    example_input: { margin_band: '45-60' }, expected_output: 'good',
    note: 'phase-margin verdict bands: the tuning rule of thumb as a table' },
  { id: 'ctl.bode-corner', kind: 'formula', family: 'control-theory', catalog_ref: 'bode-table',
    inputs: ['r'], expr: '-10 * Math.log10(1 + r*r)',
    example_input: { r: 1 }, expected_output: -3.010299956639812,
    note: 'first-order low-pass magnitude in dB at r = f/fc; the -3 dB corner' },
  { id: 'ctl.state-step', kind: 'formula', family: 'control-theory', catalog_ref: 'state-space-table',
    inputs: ['a', 'x', 'b', 'u'], expr: 'a*x + b*u',
    example_input: { a: 0.9, x: 1, b: 0.1, u: 0 }, expected_output: 0.9,
    note: 'one discrete tick of linear dynamics x(t+1) = a·x + b·u' },

  // ---- DYNAMICAL SYSTEMS (extension family) ----
  { id: 'dyn.logistic-step', kind: 'formula', family: 'dynamical-systems', catalog_ref: 'bifurcation-table',
    inputs: ['x', 'r'], expr: 'r * x * (1 - x)',
    example_input: { x: 0.5, r: 3.2 }, expected_output: 0.8 },
  { id: 'dyn.ca-rule110', kind: 'lookup', family: 'dynamical-systems', catalog_ref: 'cellular-automaton-table',
    inputs: ['triplet'], table: { '111': 0, '110': 1, '101': 1, '100': 0, '011': 1, '010': 1, '001': 1, '000': 0 }, default: 0,
    example_input: { triplet: '110' }, expected_output: 1,
    note: "wolfram rule 110: the lookup that's Turing-complete" },
  { id: 'dyn.fixed-point', kind: 'formula', family: 'dynamical-systems', catalog_ref: 'return-map-table',
    inputs: ['r'], expr: '1 - 1 / r',
    example_input: { r: 3.2 }, expected_output: 0.6875,
    note: 'logistic-map fixed point x* = 1 - 1/r; where the return map crosses the diagonal' },
  { id: 'dyn.basin', kind: 'lookup', family: 'dynamical-systems', catalog_ref: 'basin-table',
    inputs: ['initial'], table: { low: 'gentle-attractor', mid: 'oscillation', high: 'collapse' }, default: 'oscillation',
    example_input: { initial: 'high' }, expected_output: 'collapse',
    note: 'basin of attraction read directly off the initial condition' },
  { id: 'dyn.lyapunov-class', kind: 'formula', family: 'dynamical-systems', catalog_ref: 'lyapunov-table',
    inputs: ['lambda'], expr: 'lambda > 0 ? "chaotic" : lambda === 0 ? "marginal" : "stable"',
    example_input: { lambda: 0.4 }, expected_output: 'chaotic',
    note: 'largest Lyapunov exponent classifies the trajectory regime' },

  // ---- TOPOLOGY & STRUCTURE (extension family) ----
  { id: 'topo.euler', kind: 'formula', family: 'topology-structure', catalog_ref: 'euler-characteristic-table',
    inputs: ['v', 'e', 'f'], expr: 'v - e + f',
    example_input: { v: 8, e: 12, f: 6 }, expected_output: 2,
    note: 'cube: χ = 2' },
  { id: 'topo.incidence', kind: 'lookup', family: 'topology-structure', catalog_ref: 'incidence-table',
    inputs: ['ve'], table: { 'v1-e1': 1, 'v2-e1': -1, 'v2-e2': 1, 'v3-e2': -1 }, default: 0,
    example_input: { ve: 'v2-e1' }, expected_output: -1 },
  { id: 'topo.degree', kind: 'lookup', family: 'topology-structure', catalog_ref: 'adjacency-table',
    inputs: ['vertex'], table: { a: 2, b: 2, c: 1 }, default: 0,
    example_input: { vertex: 'a' }, expected_output: 2,
    note: 'degree read off an adjacency row; the 1/0 matrix pre-summed' },
  { id: 'topo.knot-crossings', kind: 'lookup', family: 'topology-structure', catalog_ref: 'knot-invariant-table',
    inputs: ['knot'], table: { unknot: 0, trefoil: 3, 'figure-eight': 4 }, default: 0,
    example_input: { knot: 'trefoil' }, expected_output: 3,
    note: 'minimal crossing number as a knot invariant row' },
  { id: 'topo.betti-euler', kind: 'formula', family: 'topology-structure', catalog_ref: 'homology-table',
    inputs: ['b0', 'b1', 'b2'], expr: 'b0 - b1 + b2',
    example_input: { b0: 1, b1: 2, b2: 1 }, expected_output: 0,
    note: 'χ = Σ(-1)^k b_k; the torus row of the homology table gives 0' },

  // ---- SUMMARY STATISTICS (wave-67 extension family: the gap wave-66's recipes exposed) ----
  { id: 'ss.pooled-mean', kind: 'formula', family: 'summary-statistics', catalog_ref: 'mean-table',
    inputs: ['m1', 'n1', 'm2', 'n2'], expr: '(m1*n1 + m2*n2) / (n1 + n2)',
    example_input: { m1: 10, n1: 2, m2: 20, n2: 3 }, expected_output: 16,
    note: 'pooled mean from a mean table\u2019s group rows: (mean\u00b7n) re-aggregated' },
  { id: 'ss.median3', kind: 'formula', family: 'summary-statistics', catalog_ref: 'median-table',
    inputs: ['a', 'b', 'c'], expr: 'a + b + c - Math.min(a, b, c) - Math.max(a, b, c)',
    example_input: { a: 7, b: 3, c: 5 }, expected_output: 5,
    note: '3-value median: sum minus the extremes, no sorting cell needed' },
  { id: 'ss.mode-count', kind: 'lookup', family: 'summary-statistics', catalog_ref: 'mode-table',
    inputs: ['observed'], table: { red: 42, blue: 17, green: 42 }, default: 0,
    example_input: { observed: 'blue' }, expected_output: 17,
    note: 'the count column IS the lookup; ties (red/green) resolved upstream' },
  { id: 'ss.quartile-band', kind: 'lookup', family: 'summary-statistics', catalog_ref: 'quartile-table',
    inputs: ['pct_rank'], table: { '<25': 'Q1', '25-50': 'Q2', '50-75': 'Q3', '75-100': 'Q4' }, default: 'Q1',
    example_input: { pct_rank: '50-75' }, expected_output: 'Q3',
    note: 'quartile membership from a percentile rank' },
  { id: 'ss.iqr-outlier', kind: 'formula', family: 'summary-statistics', catalog_ref: 'iqr-table',
    inputs: ['x', 'q1', 'q3'], expr: '(x < q1 - 1.5*(q3 - q1) || x > q3 + 1.5*(q3 - q1)) ? "outlier" : "inside"',
    example_input: { x: 20, q1: 10, q3: 12 }, expected_output: 'outlier',
    note: 'Tukey fences: 1.5\u00d7IQR beyond the quartiles flags the row' },
  { id: 'ss.midrange', kind: 'formula', family: 'summary-statistics', catalog_ref: 'five-number-summary-table',
    inputs: ['lo', 'hi'], expr: '(lo + hi) / 2',
    example_input: { lo: 2, hi: 10 }, expected_output: 6,
    note: 'midrange: the center point of the five-number summary\u2019s outer pair' },
  { id: 'ss.range', kind: 'formula', family: 'summary-statistics', catalog_ref: 'range-table',
    inputs: ['xs'], expr: 'Math.max(...xs) - Math.min(...xs)',
    example_input: { xs: [3, 9, 4] }, expected_output: 6,
    note: 'range: max-min, the crudest honest spread' },
  { id: 'ss.percentile-band', kind: 'lookup', family: 'summary-statistics', catalog_ref: 'percentile-table',
    inputs: ['pct_rank'], table: { '90+': 'top-decile', '75-90': 'upper-quartile', '25-75': 'middle', '<25': 'bottom-quartile' }, default: 'middle',
    example_input: { pct_rank: '90+' }, expected_output: 'top-decile',
    note: 'percent ranks banded into named cutoffs; growth charts run on this' },
  { id: 'ss.skewness', kind: 'formula', family: 'summary-statistics', catalog_ref: 'skewness-table',
    inputs: ['mean', 'median', 'sd'], expr: '(mean - median) / sd',
    example_input: { mean: 10, median: 8, sd: 4 }, expected_output: 0.5,
    note: 'Pearson\u2019s second skewness coefficient from the summary row' },
  { id: 'ss.kurtosis-class', kind: 'lookup', family: 'summary-statistics', catalog_ref: 'kurtosis-table',
    inputs: ['tail_weight'], table: { thin: 'light-tails', normal: 'gaussian-like', fat: 'heavy-tails' }, default: 'gaussian-like',
    example_input: { tail_weight: 'fat' }, expected_output: 'heavy-tails',
    note: 'tail-weight verdicts; the risk report\u2019s favorite column' },
  { id: 'ss.moving-average-3', kind: 'formula', family: 'summary-statistics', catalog_ref: 'moving-average-table',
    inputs: ['x1', 'x2', 'x3'], expr: '(x1 + x2 + x3) / 3',
    example_input: { x1: 1, x2: 2, x3: 6 }, expected_output: 3,
    note: '3-point window: the row the smoothing chart plots' },
  { id: 'ss.ewma-step', kind: 'formula', family: 'summary-statistics', catalog_ref: 'ewma-table',
    inputs: ['prev', 'x', 'alpha'], expr: 'alpha * x + (1 - alpha) * prev',
    example_input: { prev: 10, x: 6, alpha: 0.5 }, expected_output: 8,
    note: 'one EWMA tick: the smoothing cell in a sensor sheet' },
  { id: 'ss.cv', kind: 'formula', family: 'summary-statistics', catalog_ref: 'coefficient-of-variation-table',
    inputs: ['mean', 'sd'], expr: 'sd / mean',
    example_input: { mean: 20, sd: 5 }, expected_output: 0.25,
    note: 'relative spread, dimensionless: comparable across units' },

  // ---- GENETICS ----
  { id: 'gen.punnett', kind: 'lookup', family: 'genetics', catalog_ref: 'punnett-square-table',
    inputs: ['cross'], table: { 'AA-AA': 'AA', 'AA-Aa': 'Aa', 'Aa-Aa': 'AA,Aa,aa', 'Aa-aa': 'Aa,aa' }, default: 'Aa',
    example_input: { cross: 'AA-Aa' }, expected_output: 'Aa' },
  { id: 'gen.hardy-weinberg', kind: 'formula', family: 'genetics', catalog_ref: 'hardy-weinberg-table',
    inputs: ['q'], expr: '2 * (1 - q) * q',
    example_input: { q: 0.2 }, expected_output: 0.32 },

  // ---- FINANCE / BUSINESS (the domain the store lives in) ----
  { id: 'biz.shipping-tier', kind: 'lookup', family: 'relations-functions', catalog_ref: 'function-table',
    inputs: ['order_total_band'], table: { '0-20': 5, '20-50': 3, '50+': 0 }, default: 5,
    example_input: { order_total_band: '20-50' }, expected_output: 3 },
  { id: 'biz.refund-window', kind: 'lookup', family: 'logic', catalog_ref: 'decision-table',
    inputs: ['days_receipt'], table: { 'under7_yes': 'full-refund', 'under7_no': 'store-credit', 'over7_yes': 'manager', 'over7_no': 'manager' }, default: 'manager',
    example_input: { days_receipt: 'under7_no' }, expected_output: 'store-credit' },
];

export default RECIPES;
